services:
  api:
    build: .
    container_name: yegi_api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FRONTEND_ORIGINS=${FRONTEND_ORIGINS}
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  ollama:
    image: ollama/ollama
    container_name: yegi_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
